"""
Basic - Kage Node
Generated by Kage Framework
"""

from kage import create_main_function, Kage

def process_value(name: str, age: int) -> str:
    """Example processing function"""
    return f"Username: {name}, Age: {age}"

def configure_kage(kage: Kage) -> Kage:
    """Configure Kage instance with your functions"""
    return kage.bind_function(
        process_value,
        {"name": "user.name", "age": "user.age"},
        output_key="message"
    )

# Create main function
main = create_main_function(configure_kage)

if __name__ == "__main__":
    import sys
    sys.exit(main())